### ISSUE TITLE
Uncompressing failed. 1.4gb file created instead

### ISSUE THREAD

**Issue by montcer9012** [ucorpor/ibf-unpack#1]
Hi. Thank you for this tool. I am trying to unzip both [configini.ibf](https://archive.org/download/PS3_ALVRO_PART_1/Bioshock_BLUS30166.rar/Bioshock%20BLUS30166%2FPS3_GAME%2FUSRDIR%2Fconfigini.ibf) and [localizedint.lbf](https://archive.org/download/PS3_ALVRO_PART_1/Bioshock_BLUS30166.rar/Bioshock%20BLUS30166%2FPS3_GAME%2FUSRDIR%2Flocalizedint.lbf) for the PS3 version in order to remap the key bindings. However, when ibf-unpack tool does indeed extract it, creates a file 1.4gb large in the System folder. Maybe it is not compatible with the vanilla version of Bioshock?

**Comment by ucorpor** [comment]
Hi. PC vanilla version is supported, but the console version has a different game archives structure. In new [release](https://github.com/ucorpor/ibf-unpack/releases/tag/v1.4) I have added the ability to unpack archives of console version, but the ability to create new archive is currently available only for the PC version

**Comment by montcer9012** [comment]
Thanks, it works like a charm, even with the packed version into the last update released for PS3 ([US](http://b0.ww.np.dl.playstation.net/tppkg/np/BLUS30166/BLUS30166_T2/5efaff7c45f87723/UP1001-BLUS30166_00-BIOSHOCKPATCH001-A0110-V0100-PE.pkg), [EU](http://b0.ww.np.dl.playstation.net/tppkg/np/BLES00316/BLES00316_T9/e91d641bea397bf9/EP1001-BLES00316_00-BIOSHOCKPATCH001-A0110-V0100-PE.pkg)). I know that the PC version can boot if configini.ibf and localizedint.lbf are deleted/renamed and its content is located in the System folder. However, the PS3 version, at least the EU which I do have, doesn't. It would be great to have a release that allows to repack the files, at least configini, which have the key bindings! Shame on devs who didn't add key customizations for console versions.

PD: the unpacker has something to do with the text codification? Extracted files needs Unicode Big Endian encoding in order to be readable properly. I wonder if this may be a problem to repack it later on.

UPDATE: Again, I don't know if this may impact for future releases, but the PS3 EU vanilla configini.ibf file could be modded without unpacking, just by opening it with Notepad++, saving it, and replacing it in the games files. However, same operation couldn't be done for the updated file included in the .PKG because it needs Unicode Big Endian to be readable, and I think the text editors I am using doesn't save it back as supposed to because the game wont boot if I edit this updated version of configini.

**Comment by ucorpor** [comment]
The unpacker does not affect the text encoding. PS3 CPU (and Xbox 360 too) use big-endian endianness. So .ini and .int files for the console version use UTF-16BE encoding and the .ibf file itself also uses big-endian byte order. PC version files use little-endian endianness and UTF-16LE encoding.

Configini.ibf is not text file. You can edit it without unpacking with Hex editor ([example](https://wxmedit.github.io/)), but only by replacing existing characters. Any byte shift, e.g. adding a new character anywhere in file, will corrupting archive structure. In addition, special bytes with meta information about the files inside the archive, prevent the correct display of the files text.

**Comment by montcer9012** [comment]
That hex/text editor did the job! Now I don't need to extract the file nor to repack it, so I think this issue can be closed (?) Luckily the app would allow to repack in the future. Thanks again!
